### ISSUE TITLE
Connecting to discuss react-native-matrix-sdk

### ISSUE THREAD

**Issue by zzorba** [unomed-dev/react-native-matrix-sdk#5]
Reached out on another issue, but thought I'd send a note here that is more focused to our purpose than the crash in the main matrix-rust-sdk project.

We're working to develop this tool https://github.com/jhugman/uniffi-bindgen-react-native/, we have it working but are still working out one or two last kinks and in the process of adding full documentation to make it easier to self-serve it. 

The primary library we are working to integrate is the matrix-rust-sdk, much like you are.  The tool basically generates typescript bindings and a TurboModule from the uniffi definitions directly, and is able to take advantage of the JSI GC system and free corresponding rust objects as well.  

I'd love to connect to discuss opportunities to collaborate on an open sourced matrix-rust-sdk for react-native, feel free to shoot me an email at daniel at filament.im

**Comment by Johennes** [comment]
Thanks, we'll be in touch! 🙂
