### ISSUE TITLE
Fix x86 build

### ISSUE THREAD

**Issue by Johennes** [unomed-dev/react-native-matrix-sdk#6]
The x86 targets are currently excluded on both platforms because I couldn't get matrix-rust-sdk to build on them. Ideally we wouldn't have to exclude them.

**Comment by zzorba** [comment]
@Johennes is this the x86 simulator target?  

In the past I have managed to build that in our project using the `x86_64-apple-ios` target (one of our developers was developing on x86 until very recently).

**Comment by Johennes** [comment]
Actually, no this is about the x86 Android targets. I think you need these for some Android devices? I'm getting a build error trying to link with cargo-ndk. I think it might be something in my local environment but I haven't been able to pin it down yet.

```
error: linking with `/Users/jm/.cargo/bin/cargo-ndk` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/Users/jm/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/bin:/Users/jm/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/bin:/Users/jm/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/bin:/private/var/folders/zv/cnks6dx14rl25kvgqslhpv740000gn/T/xfs-d4f2b389:/private/var/folders/zv/cnks6dx14rl25kvgqslhpv740000gn/T/...
  = note: ld.lld: error: unable to find library -lclang_rt.builtins-x86_64-android
          clang-17: error: linker command failed with exit code 1 (use -v to see invocation)
```

Ironically `x86_64-apple-ios` gives me another error. But I think this one may have been fixed in ubrn since I last updated the version here.

```
Running "lipo" "-create" "/Users/jm/Code/react-native-matrix-sdk/rust_modules/matrix-rust-sdk/target/aarch64-apple-ios-sim/debug/libmatrix_sdk_ffi.a" "/Users/jm/Code/react-native-matrix-sdk/rust_modules/matrix-rust-sdk/target/x86_64-apple-ios/debug/libmatrix_sdk_ffi.a" "-output" "/Users/jm/Code/react-native-matrix-sdk/rust_modules/matrix-rust-sdk/target/lipo/ios-simulator/libmatrix_sdk_ffi.a"
Running cd "/Users/jm/Code/react-native-matrix-sdk/ios" && "xcodebuild" "-create-xcframework" "-library" "/Users/jm/Code/react-native-matrix-sdk/rust_modules/matrix-rust-sdk/target/lipo/ios-simulator/libmatrix_sdk_ffi.a" "-library" "/Users/jm/Code/react-native-matrix-sdk/rust_modules/matrix-rust-sdk/target/aarch64-apple-ios/debug/libmatrix_sdk_ffi.a" "-output" "/Users/jm/Code/react-native-matrix-sdk/build/RnMatrixRustSdk.xcframework"
xcframework successfully written out to: /Users/jm/Code/react-native-matrix-sdk/build/RnMatrixRustSdk.xcframework
Error: Failed to extract data from archive member `matrix_sdk_ffi.3p547y0x3mnf5geuf7zavbad8.rcgu.o`

Caused by:
    Unknown library format
```

**Comment by Johennes** [comment]
Actually the iOS issue isn't solved on the latest ubrn release. Have reopened https://github.com/jhugman/uniffi-bindgen-react-native/issues/136.

**Comment by Johennes** [comment]
I've been able to fix the Android issue in https://github.com/unomed-dev/react-native-matrix-sdk/pull/15 by setting `CARGO_TARGET_X86_64_LINUX_ANDROID_RUSTFLAGS="-L$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-x86_64/lib/clang/17/lib/linux"`. Interestingly this wasn't required on the CI and on my local machine the x86-64 target was the only one that needed the fix.

**Comment by Johennes** [comment]
Temporarily fixed the iOS x86 build with https://github.com/unomed-dev/react-native-matrix-sdk/pull/16 by using `ubrn generate all --config ubrn.yaml build/RnMatrixRustSdk.xcframework/ios-arm64/libmatrix_sdk_ffi.a`.
