### ISSUE TITLE
Initialisation example

### ISSUE THREAD

**Issue by olliiiver** [unomed-dev/react-native-matrix-sdk#9]
Hello.

First of all, thank you for making this library available. 

I'm currently playing around with it and was wondering if you could provide a more detailed example how to initialise a working connection.

My additions to App.tsx from example folder:

```
const client = await (new ClientBuilder()).homeserverUrl(homeserver).build();
const loginDetails = await client.homeserverLoginDetails();
      
// works
await client.login("@...:matrix.org", "...", "Test", "Test");

// works
await client.createRoom({
        name: "Test Room",
        topic: "test",
        isEncrypted: false,
        isDirect: false,
        visibility: RoomVisibility.Public,
        preset: RoomPreset.PublicChat,
        invite: [],
        avatar: "",
        powerLevelContentOverride: undefined
});

// is empty
const rooms = client.rooms();
console.log(rooms);

// fails with exception
await client.syncService().finish();

```

Any help would be greatly appreciated!

**Comment by Johennes** [comment]
Hey, the example in `App.tsx` is fairly minimal, yes. I haven't gotten around to expanding it yet but contributions would definitely be welcome.

For your particular case, after logging in, you need to start a `SyncService` instance. From there you can access the room list service and start listening to updates of the room list.

Sadly, the FFI bindings for matrix-rust-sdk don't really have official documentation but you can get an idea from https://github.com/matrix-org/matrix-rust-components-swift/blob/main/docs/Getting%20Started.md.

I have a few custom hooks that I'm using in a proprietary app that I'm hoping to eventually add to this repository, too, but again for shortage of time didn't get around to it so far.

**Comment by olliiiver** [comment]
Hi @Johennes. Thank you. That was very helpful. 😄 

The following code works for me ...

```
      const tempDir = RNFS.TemporaryDirectoryPath;
      console.log("Temp dir:" + tempDir);
      const dataDir = RNFS.DocumentDirectoryPath + "/data";
      const cacheDir = RNFS.DocumentDirectoryPath + "/cache";

      const client = await (new ClientBuilder()
        .serverNameOrHomeserverUrl(homeserver)
        .sessionPaths(dataDir, cacheDir)
        .slidingSyncVersionBuilder(new SlidingSyncVersionBuilder.DiscoverProxy())
        .build());
      
      await client.login("@...:matrix.org", "...", "Test", "Test");

      client.session();
     
      const syncService = await client.syncService().finish();

      await syncService.start();

      console.log(client.userId());

      const rooms = client.rooms();
      rooms.forEach((r) => {
        console.log(r.id()+ " " + r.rawName());
      })
```
